[package]
name = "coevolution-huegene-model"
version = "0.1.0"
authors = ["bigbass1997 <bigbass1997.website@gmail.com>"]
edition = "2021"


[dependencies]
minifb = "0.22"
oorandom = "11.1.3"
gif = "0.11.1"
time = { version = "0.3", features = ["formatting"] }
image = "0.24"
palette = "0.6"
